# Generated by Django 2.2.7 on 2019-11-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='frame_name',
            new_name='framework_name',
        ),
    ]
