# Generated by Django 2.2.7 on 2019-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191124_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_school', models.CharField(max_length=50)),
                ('exam_gpa', models.FloatField()),
                ('exam_year', models.SmallIntegerField()),
            ],
        ),
    ]
