# Generated by Django 2.2.7 on 2019-12-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(max_length=1, upload_to='images/'),
        ),
    ]
