# Generated by Django 2.2.7 on 2019-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20191208_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
