# Generated by Django 3.0 on 2019-12-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20191208_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
