# Generated by Django 3.0 on 2020-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20191211_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='obj',
            field=models.TextField(blank=True),
        ),
    ]
